### ISSUE TITLE
KeyError when creating event with unsupported language

### ISSUE THREAD

**Issue by jevinjojo** [fossasia/eventyay#1388]
**Describe the bug**
When creating a new event with an unsupported language, the system allows the event to be created and added to the event list. 

**Steps to Reproduce**
* Create a new event and Select a language 
* Enter an event name in a language which doesn't match the selected language 
* Set the default language to an unsupported language and submit the event 

**Expected behavior**
* The event creation form should validate the language code against supported languages
*  Event should not be created or added to the event list if the language code is invalid

**Screenshots**

<img width="1314" height="488" alt="Image" src="https://github.com/user-attachments/assets/eca5eab0-900f-4c1e-8318-a6d1afdad628" />

**Comment by jevinjojo** [comment]
@mariobehling is this a known issue and already working on this?

**Comment by mariobehling** [comment]
Actually I am unclear what are unsupported languages. If a language wrong it should be fixed or removed from our system. The language code "ua" is wrong and should be removed. The correct language code for Ukrainian is "uk". Which other languages cause this error?

**Comment by jevinjojo** [comment]
> Actually I am unclear what are unsupported languages. If a language wrong it should be fixed or removed from our system. The language code "ua" is wrong and should be removed. The correct language code for Ukrainian is "uk". Which other languages cause this error?

the error happens whenever we create any language combination that includes Ukrainian. even it provides the correct language input for Ukrainian, it still throws those errors also created the event and when viewing it same error appears. 

for other languages excluding Ukrainian if we enter the incorrect inputs, the event still gets created without that error

**Comment by mariobehling** [comment]
Thanks. I updated the title. A fix would involve Ukrainian language therefore.

**Comment by hongquan** [comment]
@jevinjojo 
Could you provide the concrete language names in these reproducing steps:

>     Create a new event and Select a language
>     Enter an event name in a language which doesn't match the selected language
>     Set the default language to an unsupported language and submit the event

I asked because if none of them use `Ukraine`, but the system raised error regarding to "Unkraine", then our system has some more bugs.

**Comment by jevinjojo** [comment]
@hongquan At first I created the event with only Ukrainian (default) using the correct language code and valid event name in Ukrainian. 

<img width="474" height="185" alt="Image" src="https://github.com/user-attachments/assets/6163ccbb-b75a-4b79-9e07-713c15ebff7e" />

<img width="1527" height="877" alt="Image" src="https://github.com/user-attachments/assets/f5dde9ba-82d4-4ab6-ba57-47f192aae32a" /> <img width="1275" height="879" alt="Image" src="https://github.com/user-attachments/assets/767e85f0-4d09-445c-8c27-6b87451d3d3a" />

I also tested with multiple languages selected — English, German, Russian, and Ukrainian — all with valid names.  default language was set to English. 

<img width="411" height="185" alt="Image" src="https://github.com/user-attachments/assets/8a8750d3-d24d-48ec-b77a-30dd30a5032b" />

<img width="1106" height="844" alt="Image" src="https://github.com/user-attachments/assets/3f1e2369-98a2-4c28-b4e9-878954519ab7" />

<img width="1283" height="904" alt="Image" src="https://github.com/user-attachments/assets/03f6b6f3-6f32-4311-8ab2-605e19acdc2d" />

the issue only occurs when Ukrainian is included whether the event name is correct or incorrect, if Ukrainian is selected, the event gets created keyerror shown and viewing it triggers the error 

LMK if this works

**Comment by Saksham-Sirohi** [comment]
the issue no longer exists as i cannot find the ua reference lingering anywhere also an event created with the ukranian language seem to be working fine
